package orders;

import java.io.IOException;
import java.sql.Connection;
import java.sql.Statement;
import java.util.Properties;

import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import pojo.Order;
import pojo.Sproduct;
import connection.ProjectConn;
import dao.UserDao;

/**
 * Servlet implementation class ConfirmOrder
 */
public class ConfirmOrder extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public ConfirmOrder() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.getWriter().append("Served at: ").append(request.getContextPath());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException,IOException {
		
		int orderid = Integer.parseInt(request.getParameter("orderId"));
		Integer id = Integer.parseInt(request.getParameter("uid"));
		String[] productadd = request.getParameterValues("productadd");
		String date = request.getParameter("date");
		double amount = Double.parseDouble(request.getParameter("amount"));
		String[] price = request.getParameterValues("price");
		String[] total = request.getParameterValues("total");
		String[] qty = request.getParameterValues("qty");

		/*---------------show email---------------*/

		double grandtotal = Double.parseDouble(request.getParameter("grandtotal"));
		double discount = 0.0;
		String discountParam = request.getParameter("discount");
		if (discountParam != null && !discountParam.isEmpty()) {
			discount = Double.parseDouble(discountParam);
		}
		String name = request.getParameter("name");
		double Total = Double.parseDouble(request.getParameter("Total"));
		String to = request.getParameter("email");
		String address1 = request.getParameter("address1");
		String city = request.getParameter("city");
		String country = request.getParameter("country");
		String state = request.getParameter("state");

		// Generate HTML content for the current product
		String productHTML = ""
				+ "<body class='clean-body' style='margin: 0; padding: 0;-webkit-text-size-adjust: 100%; background-color: #f2fafc;'>"
				+ "<table bgcolor='#f2fafc' cellpadding='0' cellspacing='0' class='nl-container' role='presentation' style='table-layout: fixed; vertical-align: top; min-width: 320px; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f2fafc; width: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td style='word-break: break-word; vertical-align: top' valign='top'>"
				+ "<div style='background-color: #fb3c2d'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<table border='0' cellpadding='0' cellspacing='0' class='divider' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td class='divider_inner' style='word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;' valign='top'>"
				+ "<table align='center' border='0' cellpadding='0' cellspacing='0' class='divider_content' height='01' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 01px; width: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td height='1' style='word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top'>"
				+ "<span>"
				+ "</span>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<table border='0' cellpadding='0' cellspacing='0' class='divider' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td class='divider_inner' style='word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;' valign='top'>"
				+ "<table align='center' border='0' cellpadding='0' cellspacing='0' class='divider_content' height='5' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 5px; width: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td height='5' style='word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top'>"
				+ "<span>"
				+ "</span>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"

				+ "</div>"

				+ "</div>"
				+ "</div>"

				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"

				+ "<div align='center' class='img-container center fixedwidth' style='padding-right: 0px; padding-left: 0px'>"

				+ "</div>"
				+ "<div style='color: #44464a; .align: center; font-family: 'Playfair Display', Georgia, serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; font-family: 'Playfair Display', Georgia, serif; color: #44464a; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 30px; line-height: 1.2; word-break: break-word; text-align: center; font-family: 'Playfair Display', Georgia, serif; mso-line-height-alt: 36px; margin: 0;'>"
				+ "<h2 align='center'>Thank you for shopping with us!</h2>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "<div align='center' class='img-container center fixedwidth' style='padding-right: 25px; padding-left: 25px'>"
				+ "<div style='font-size: 1px; line-height: 25px'>"
				+ "</div>"
				+ "<p><a href='http://localhost:8080/Shoe_Store/index.jsp'>Shoe Store</a></p>"
				+ "<div style='font-size: 1px; line-height: 25px'>"
				+ "</div>"
				+ "<div style='line-height: 1.2; font-size: 12px; color: #44464a; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<h3>Shipping Address</h3>" + "<p>"
				+ address1
				+ ", "
				+ city
				+ ", "
				+ state
				+ ", "
				+ country
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid mixed-two-up' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: #ffffff;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: #ffffff;'>"
				+ "<div class='col num8' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 448px; width: 453px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 15px; padding-bottom: 5px; padding-right: 10px; padding-left: 10px;'>"
				+ "<div style='color: #44464a; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #44464a; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 14px; line-height: 1.2; word-break: break-word; mso-line-height-alt: 17px; margin: 0;'>Customer Name:<span style='color: #fb3c2d'>"
				+ "<strong> "
				+ name
				+ "</strong>"
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "<div style='color: #44464a; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #44464a; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 14px; line-height: 1.2; word-break: break-word; mso-line-height-alt: 17px; margin: 0;'>Order number:<span style='color: #fb3c2d'>"
				+ "<strong> "
				+ orderid
				+ "</strong>"
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "<div style='color: #44464a; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #44464a; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 14px; line-height: 1.2; word-break: break-word; mso-line-height-alt: 17px; margin: 0;'>Invoice Date: "
				+ date
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 15px; padding-right: 0px; padding-left: 0px;'>"
				+ "<div class='mobile_hide'>"
				+ "<table border='0' cellpadding='0' cellspacing='0' class='divider' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td class='divider_inner' style='word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;' valign='top'>"
				+ "<table align='center' border='0' cellpadding='0' cellspacing='0' class='divider_content' height='15' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 15px; width: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td height='15' style='word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top'>"
				+ "<span>"
				+ "</span>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</div>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='680' style='background-color:transparent;width:680px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<table border='0' cellpadding='0' cellspacing='0' class='divider' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td class='divider_inner' style='word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;' valign='top'>"
				+ "<table align='center' border='0' cellpadding='0' cellspacing='0' class='divider_content' height='15' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 15px; width: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td height='15' style='word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top'>"
				+ "<span>"
				+ "</span>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid three-up no-stack' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 15px; padding-left: 15px; padding-top:5px; padding-bottom:5px;background-color:#f9feff;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; background-color: #f9feff; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 15px; padding-left: 15px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #fb3c2d; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #fb3c2d; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 14px; line-height: 1.2; word-break: break-word; mso-line-height-alt: 17px; margin: 0;'>Item</p>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if mso]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 15px; padding-left: 15px; padding-top:5px; padding-bottom:5px;background-color:#f9feff;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; background-color: #f9feff; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 15px; padding-left: 15px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #fb3c2d; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #fb3c2d; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 14px; line-height: 1.2; word-break: break-word; text-align: center; mso-line-height-alt: 17px; margin: 0;'>Quantity</p>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if mso]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 15px; padding-left: 15px; padding-top:5px; padding-bottom:5px;background-color:#f9feff;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; background-color: #f9feff; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 15px; padding-left: 15px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #fb3c2d; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #fb3c2d; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 14px; line-height: 1.2; word-break: break-word; text-align: right; mso-line-height-alt: 17px; margin: 0;'>Price</p>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if mso]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>" + "</td>" + "</tr>" + "</table>" + "<![endif]-->" + "</div>" + "</div>" + "</div>";

		for (int ii = 0; ii < productadd.length; ii++) {
			String item = productadd[ii];
			String quantity = qty[ii];
			String pricess = price[ii];

			String productInfo = "<div style='background-color: transparent'>"
					+ "<div class='block-grid three-up no-stack' style=' min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent; ' >"
					+ "<div style=' border-collapse: collapse; display: table; width: 100%; background-color: transparent; ' >"
					+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
					+ "<tr>"
					+ "<td align='center'>"
					+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
					+ "<tr class='layout-full-width' style='background-color:transparent'>"
					+ "<![endif]-->"
					+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
					+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
					+ "<tr>"
					+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
					+ "<![endif]-->"
					+ "<div class='col num4' style=' display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px; ' >"
					+ "<div class='col_cont' style='width: 100% !important'>"
					+ "<!--[if (!mso)&(!IE)]>"
					+ "<!-->"
					+ "<div style=' border-top: 0px solid transparent;  border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px; ' >"
					+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
					+ "<tr>"
					+ "<td style='padding-right: 0px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
					+ "<![endif]-->"
					+ "<div style=' color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 0px; padding-bottom: 10px;  padding-left: 10px; ' >"
					+ "<div class='txtTinyMce-wrapper' style=' line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px; ' >"
					+ "<p style=' font-size: 14px; line-height: 1.2; word-break: break-word; mso-line-height-alt: 17px; margin: 0; ' >"
					+ item
					+ "</p>"
					+ "</div>"
					+ "</div>"
					+ "<!--[if mso]>"
					+ "</td>"
					+ "</tr>"
					+ "</table>"
					+ "<![endif]-->"
					+ "<!--[if (!mso)&(!IE)]>"
					+ "<!-->"
					+ "</div>"
					+ "</div>"
					+ "</div>"
					+ "<!--[if (mso)|(IE)]>"
					+ "</td>"
					+ "</tr>"
					+ "</table>"
					+ "<![endif]-->"
					+ "<!--[if (mso)|(IE)]>"
					+ "</td>"
					+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
					+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
					+ "<tr>"
					+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
					+ "<![endif]-->"
					+ "<div class='col num4' style=' display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px;  width: 226px; ' >"
					+ "<div class='col_cont' style='width: 100% !important'>"
					+ "<!--[if (!mso)&(!IE)]>"
					+ "<!-->"
					+ "<div style=' border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px; ' >"
					+ "<!--[if mso]>"
					+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
					+ "<tr>"
					+ "<td style='padding-right: 5px; padding-left: 5px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
					+ "<![endif]-->"
					+ "<div style=' color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2;  padding-top: 10px; padding-right: 5px;  padding-bottom: 10px;  padding-left: 5px; ' >"
					+ "<div class='txtTinyMce-wrapper' style=' line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif;  mso-line-height-alt: 14px;  ' >"
					+ "<p style=' font-size: 14px; line-height: 1.2; word-break: break-word; text-align: center; mso-line-height-alt: 17px; margin: 0; ' >"
					+ quantity
					+ "</p>"
					+ "</div>"
					+ "</div>"

					+ "</div>"

					+ "</div>"
					+ "</div>"

					+ "<div class='col num4' style=' display: table-cell; vertical-align: top; max-width: 320px;  min-width: 224px;  width: 226px; ' >"
					+ "<div class='col_cont' style='width: 100% !important'>"
					+ "<!--[if (!mso)&(!IE)]>"
					+ "<!-->"
					+ "<div style=' border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px; ' >"
					+ "<!--[if mso]>"
					+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
					+ "<tr>"
					+ "<td style='padding-right: 10px; padding-left: 0px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
					+ "<![endif]-->"
					+ "<div style=' color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 0px; ' >"
					+ "<div class='txtTinyMce-wrapper' style=' line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px; ' >"
					+ "<p style=' font-size: 14px; line-height: 1.2; word-break: break-word; text-align: right; mso-line-height-alt: 17px; margin: 0; ' >"
					+ "&#8377;"
					+ pricess
					+ "</p>"
					+ "</div>"
					+ "</div>"
					+ "<!--[if mso]>"
					+ "</td>"
					+ "</tr>"
					+ "</table>"
					+ "<![endif]-->"
					+ "<!--[if (!mso)&(!IE)]>"
					+ "<!-->"
					+ "</div>"
					+ "</div>"
					+ "</div>"
					+ "<!--[if (mso)|(IE)]>"
					+ "</td>"
					+ "</tr>"
					+ "</table>"
					+ "<![endif]-->"
					+ "<!--[if (mso)|(IE)]>"
					+ "</td>"
					+ "</tr>"
					+ "</table>"
					+ "</td>"
					+ "</tr>"
					+ "</table>"
					+ "<![endif]-->"
					+ "</div>"
					+ "</div>" + "</div>";
			productHTML += productInfo;
		}

		String fullHTML = "<div style='background-color: transparent'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='680' style='background-color:transparent;width:680px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<table border='0' cellpadding='0' cellspacing='0'class='divider' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td class='divider_inner' style='word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;' valign='top'>"
				+ "<table align='center' border='0' cellpadding='0' cellspacing='0' class='divider_content' height='1' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 1px solid #e1ecef; height: 1px; width: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td height='1' style='word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top'>"
				+ "<span>"
				+ "</span>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid three-up no-stack' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper'style='line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 16px; line-height: 1.2; word-break: break-word; mso-line-height-alt: 19px; margin: 0;'>"
				+ "<span style='font-size: 16px'>"
				+ "<strong>Total</strong>"
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if mso]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<div>"
				+ "</div>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 16px; line-height: 1.2; word-break: break-word; text-align: right; mso-line-height-alt: 19px; margin: 0;'>"
				+ "<span style='font-size: 16px'>" + "&#8377;"
				+ Total
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid three-up no-stack' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper'style='line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 16px; line-height: 1.2; word-break: break-word; mso-line-height-alt: 19px; margin: 0;'>"
				+ "<span style='font-size: 16px'>"
				+ "<strong>Shipping Charge</strong>"
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if mso]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<div>"
				+ "</div>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 16px; line-height: 1.2; word-break: break-word; text-align: right; mso-line-height-alt: 19px; margin: 0;'>"
				+ "<span style='font-size: 16px'>&#8377;50</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid three-up no-stack' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper'style='line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 16px; line-height: 1.2; word-break: break-word; mso-line-height-alt: 19px; margin: 0;'>"
				+ "<span style='font-size: 16px'>"
				+ "<strong>Grand Total</strong>"
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if mso]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<div>"
				+ "</div>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 16px; line-height: 1.2; word-break: break-word; text-align: right; mso-line-height-alt: 19px; margin: 0;'>"
				+ "<span style='font-size: 16px'>&#8377;"
				+ grandtotal
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid three-up no-stack' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper'style='line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 16px; line-height: 1.2; word-break: break-word; mso-line-height-alt: 19px; margin: 0;'>"
				+ "<span style='font-size: 16px'>"
				+ "<strong>Discount</strong>"
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if mso]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<div>"
				+ "</div>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "<td align='center' width='226' style='background-color:transparent;width:226px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num4' style='display: table-cell; vertical-align: top; max-width: 320px; min-width: 224px; width: 226px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #393d47; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 16px; line-height: 1.2; word-break: break-word; text-align: right; mso-line-height-alt: 19px; margin: 0;'>"
				+ "<span style='font-size: 16px'>&#8377;-"
				+ discount
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<table border='0' cellpadding='0' cellspacing='0' class='divider' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td class='divider_inner' style='word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;' valign='top'>"
				+ "<table align='center' border='0' cellpadding='0' cellspacing='0' class='divider_content' height='1' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 1px solid #e1ecef; height: 1px; width: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td height='1' style='word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top'>"
				+ "<span>"
				+ "</span>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='680' style='background-color:transparent;width:680px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 5px; padding-left: 5px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 5px; padding-left: 5px;'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; font-family: Arial, sans-serif'>"
				+ "<![endif]-->"
				+ "<div style='color: #fb3c2d; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; line-height: 1.2; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;'>"
				+ "<div class='txtTinyMce-wrapper' style='line-height: 1.2; font-size: 12px; color: #fb3c2d; font-family: Nunito, Arial, Helvetica Neue, Helvetica, sans-serif; mso-line-height-alt: 14px;'>"
				+ "<p style='font-size: 22px; line-height: 1.2; word-break: break-word; text-align: right; mso-line-height-alt: 26px; margin: 0;'>"
				+ "<span style='font-size: 22px'>"
				+ "<strong>"
				+ "<span style=''>Total &#8377;"
				+ amount
				+ "</span>"
				+ "</strong>"
				+ "</span>"
				+ "</p>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if mso]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='680' style='background-color:transparent;width:680px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<table border='0' cellpadding='0' cellspacing='0' class='divider' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td class='divider_inner' style='word-break: break-word; vertical-align: top; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px;' valign='top'>"
				+ "<table align='center' border='0' cellpadding='0' cellspacing='0' class='divider_content' height='40' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-top: 0px solid transparent; height: 40px; width: 100%;'valign='top' width='100%'>"
				+ "<tbody>"
				+ "<tr style='vertical-align: top' valign='top'>"
				+ "<td height='40' style='word-break: break-word; vertical-align: top; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top'>"
				+ "<span>"
				+ "</span>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='680' style='background-color:transparent;width:680px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px;'>"
				+ "<![endif]-->"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 5px; padding-bottom: 5px; padding-right: 0px; padding-left: 0px;'>"
				+ "<table border='0' cellpadding='0' cellspacing='0' class='divider' role='presentation'style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; min-width: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;' valign='top' width='100%'>"
				+ "</table>"
				+ "<div align='center' class='img-container center fixedwidth' style='padding-right: 25px; padding-left: 25px'>"
				+ "<!--[if mso]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr style='line-height:0px'>"
				+ "<td style='padding-right: 25px;padding-left: 25px;' align='center'>"
				+ "<![endif]-->"
				+ "<div style='font-size: 1px; line-height: 25px'>"
				+ "</div>"
				+ "<small style='color: #7a899f;'>&copy;2023 Copyright<a href='http://localhost:8080/Shoe_Store/index.jsp' target='_blank'style='text-decoration: none; color: #1f74ca;'> Shoe Store </a>All Rights Reserved.</small>"
				+ "<div style='font-size: 1px; line-height: 25px'>"
				+ "</div>"
				+ "<!--[if mso]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "</div>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "</td>"
				+ "</tr>"
				+ "</table>"
				+ "<![endif]-->"
				+ "</div>"
				+ "</div>"
				+ "</div>"

				+ "<div style='background-color: transparent'>"
				+ "<div class='block-grid' style='min-width: 320px; max-width: 680px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; margin: 0 auto; background-color: transparent;'>"
				+ "<div style='border-collapse: collapse; display: table; width: 100%; background-color: transparent;'>"
				+ "<!--[if (mso)|(IE)]>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background-color:transparent;'>"
				+ "<tr>"
				+ "<td align='center'>"
				+ "<table cellpadding='0' cellspacing='0' border='0' style='width:680px'>"
				+ "<tr class='layout-full-width' style='background-color:transparent'>"
				+ "<![endif]-->"
				+ "<!--[if (mso)|(IE)]>"
				+ "<td align='center' width='680' style='background-color:transparent;width:680px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;' valign='top'>"
				+ "<table width='100%' cellpadding='0' cellspacing='0' border='0'>"
				+ "<tr>"
				+ "<td style='padding-right: 0px; padding-left: 0px; padding-top:15px; padding-bottom:15px;'>"
				+ "<![endif]-->"
				+ "<div class='col num12' style='min-width: 320px; max-width: 680px; display: table-cell; vertical-align: top; width: 680px;'>"
				+ "<div class='col_cont' style='width: 100% !important'>"
				+ "<!--[if (!mso)&(!IE)]>"
				+ "<!-->"
				+ "<div style='border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top: 15px; padding-bottom: 15px; padding-right: 0px; padding-left: 0px;'>"

				+ "<table cellpadding='0' cellspacing='0' class='social_icons' role='presentation' style='table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;' valign='top' width='100%'>"
				+ "</table>"

				+ "</div>"

				+ "</div>" + "</div>"

				+ "</div>" + "</div>" + "</div>"

				+ "</td>" + "</tr>" + "</tbody>" + "</table>"

				+ "</body>";

		productHTML += fullHTML;

		final String from = "dhusain4.3.2000@gmail.com";
		final String password = "ldqdghcizxtuqciy";
		String content = productHTML;

		Properties properties = new Properties();
		properties.put("mail.smtp.host", "smtp.gmail.com");
		properties.put("mail.smtp.socketFactory.port", "465");
		properties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
		properties.put("mail.smtp.auth", "true");
		properties.put("mail.smtp.port", "465");

		Session session2 = Session.getInstance(properties, new Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(from, password);
			}
		});

		try {
			MimeMessage message = new MimeMessage(session2);
			message.setFrom(new InternetAddress(from));
			message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
			message.setSubject("Order Placed");
			message.setContent(content, "text/html; charset=utf-8");

			Transport.send(message);

			UserDao udao = new UserDao();

			Order oid = udao.getOrderById(orderid);

			if (productadd != null) {
				for (int i = 0; i < productadd.length; i++) {
					String product = productadd[i];
					String totals = total[i];
					String qtys = qty[i];
					String prices = price[i];

					Sproduct sp = new Sproduct();
					sp.setOrder(oid);
					sp.setPname(product);
					sp.setPrice(prices);
					sp.setTotal(totals);
					sp.setQty(qtys);
					udao.addsproduct(sp);

					HttpSession sesHttpSession = request.getSession();
					sesHttpSession.setAttribute("sproduct", sp);
				}

			}

			try {
				Connection conn = ProjectConn.createConnection();
				Statement st = conn.createStatement();
				st.executeUpdate("delete from cart where uid='" + id + "' ");

			} catch (Exception e) {
				e.printStackTrace();
			}

			try {
				Connection conn = ProjectConn.createConnection();
				Statement st = conn.createStatement();
				st.executeUpdate("delete from usercoupon where uid='" + id + "' ");

			} catch (Exception e) {
				e.printStackTrace();
			}

			HttpSession session = request.getSession();
			session.removeAttribute("shipping");

			RequestDispatcher rd = request.getRequestDispatcher("dashboard.jsp?msg=done");
			rd.include(request, response);

		} catch (MessagingException e) {
			e.printStackTrace();
		}
	}
}
