package pojo;

// Generated 12 Sep, 2023 12:36:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "shoe_store")
public class Category implements java.io.Serializable {

	private Integer id;
	private String cname;
	private String cimage;
	private Set<Slider> sliders = new HashSet<Slider>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public Category() {
	}

	public Category(String cname, String cimage, Set<Slider> sliders, Set<Product> products) {
		this.cname = cname;
		this.cimage = cimage;
		this.sliders = sliders;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cname", length = 150)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "cimage", length = 300)
	public String getCimage() {
		return this.cimage;
	}

	public void setCimage(String cimage) {
		this.cimage = cimage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Slider> getSliders() {
		return this.sliders;
	}

	public void setSliders(Set<Slider> sliders) {
		this.sliders = sliders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
