package pojo;

// Generated 12 Sep, 2023 12:36:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "coupon", catalog = "shoe_store")
public class Coupon implements java.io.Serializable {

	private Integer id;
	private String code;
	private String type;
	private Integer value;
	private Integer mvalue;

	public Coupon() {
	}

	public Coupon(String code, String type, Integer value, Integer mvalue) {
		this.code = code;
		this.type = type;
		this.value = value;
		this.mvalue = mvalue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "value")
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	@Column(name = "mvalue")
	public Integer getMvalue() {
		return this.mvalue;
	}

	public void setMvalue(Integer mvalue) {
		this.mvalue = mvalue;
	}

}
