package pojo;

// Generated 12 Sep, 2023 12:36:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "shoe_store")
public class Order implements java.io.Serializable {

	private Integer id;
	private ShippingAddress shippingAddress;
	private User user;
	private String odate;
	private Double total;
	private Double amount;
	private Integer status;
	private String cancelorder;
	private Double discount;
	private Double charge;
	private Set<Sproduct> sproducts = new HashSet<Sproduct>(0);

	public Order() {
	}

	public Order(ShippingAddress shippingAddress, User user, String odate, Double total, Double amount, Integer status,
			String cancelorder, Double discount, Double charge, Set<Sproduct> sproducts) {
		this.shippingAddress = shippingAddress;
		this.user = user;
		this.odate = odate;
		this.total = total;
		this.amount = amount;
		this.status = status;
		this.cancelorder = cancelorder;
		this.discount = discount;
		this.charge = charge;
		this.sproducts = sproducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sid")
	public ShippingAddress getShippingAddress() {
		return this.shippingAddress;
	}

	public void setShippingAddress(ShippingAddress shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "odate", length = 100)
	public String getOdate() {
		return this.odate;
	}

	public void setOdate(String odate) {
		this.odate = odate;
	}

	@Column(name = "total", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "cancelorder", length = 100)
	public String getCancelorder() {
		return this.cancelorder;
	}

	public void setCancelorder(String cancelorder) {
		this.cancelorder = cancelorder;
	}

	@Column(name = "discount", precision = 22, scale = 0)
	public Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	@Column(name = "charge", precision = 22, scale = 0)
	public Double getCharge() {
		return this.charge;
	}

	public void setCharge(Double charge) {
		this.charge = charge;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Sproduct> getSproducts() {
		return this.sproducts;
	}

	public void setSproducts(Set<Sproduct> sproducts) {
		this.sproducts = sproducts;
	}

}
