package pojo;

// Generated 12 Sep, 2023 12:36:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sproduct generated by hbm2java
 */
@Entity
@Table(name = "sproduct", catalog = "shoe_store")
public class Sproduct implements java.io.Serializable {

	private Integer id;
	private Order order;
	private String pid;
	private String pname;
	private String price;
	private String qty;
	private String total;

	public Sproduct() {
	}

	public Sproduct(Order order, String pid, String pname, String price, String qty, String total) {
		this.order = order;
		this.pid = pid;
		this.pname = pname;
		this.price = price;
		this.qty = qty;
		this.total = total;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oid")
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "pid", length = 1000)
	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	@Column(name = "pname", length = 300)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "price", length = 1000)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "qty", length = 1000)
	public String getQty() {
		return this.qty;
	}

	public void setQty(String qty) {
		this.qty = qty;
	}

	@Column(name = "total", length = 1000)
	public String getTotal() {
		return this.total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

}
