package pojo;

// Generated 12 Sep, 2023 12:36:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Zip generated by hbm2java
 */
@Entity
@Table(name = "zip", catalog = "shoe_store")
public class Zip implements java.io.Serializable {

	private Integer id;
	private Integer zips;

	public Zip() {
	}

	public Zip(Integer zips) {
		this.zips = zips;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "zips")
	public Integer getZips() {
		return this.zips;
	}

	public void setZips(Integer zips) {
		this.zips = zips;
	}

}
